MATRIX_SIZE = 1000
NUM_CORES = 8
NUM_CHILD_PROCS = 8

CC = gcc
COMMON_CFLAGS = -Wall -D MATRIX_SIZE=$(MATRIX_SIZE)
PROGRAMS = gen-mat IPC-pipe IPC-shmem verify

IPC-pipe IPC-shmem: IPC_CFLAGS = -D NUM_CORES=$(NUM_CORES) -D NUM_CHILD_PROCS=$(NUM_CHILD_PROCS)

all: $(PROGRAMS)

%: %.c
	$(CC) $(COMMON_CFLAGS) $(IPC_CFLAGS) -o $@ $<

clean:
	rm -f $(PROGRAMS)